# Generated by Django 5.2.10 on 2026-01-18 18:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TruckClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'Small Van', '2-Axle Truck', '3-Axle Truck'", max_length=100, unique=True)),
                ('base_km_per_liter', models.FloatField(help_text='Fuel efficiency when empty (km/L)', validators=[django.core.validators.MinValueValidator(1.0)])),
                ('loaded_multiplier', models.FloatField(default=0.85, help_text='Multiplier applied to base km/L when loaded (e.g., 0.85 = 15% reduction)', validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(1.0)])),
                ('is_active', models.BooleanField(default=True, help_text="Inactive classes don't appear in selection forms")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Truck Classes',
                'ordering': ['name'],
            },
        ),
    ]
